// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TalkingTurkishEf;

namespace TalkingTurkishEf.Migrations
{
    [DbContext(typeof(TalkingTurkishDbContext))]
    partial class TalkingTurkishDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("TalkingTurkishEf.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("TalkingTurkishEf.Entities.Thing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Content");

                    b.Property<string>("PictureName");

                    b.Property<string>("Text");

                    b.Property<Guid?>("VoiceId");

                    b.HasKey("Id");

                    b.HasIndex("VoiceId");

                    b.ToTable("Things");
                });

            modelBuilder.Entity("TalkingTurkishEf.Entities.Voice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Content");

                    b.Property<Guid?>("LanguangeId");

                    b.HasKey("Id");

                    b.HasIndex("LanguangeId");

                    b.ToTable("Voices");
                });

            modelBuilder.Entity("TalkingTurkishEf.Entities.Thing", b =>
                {
                    b.HasOne("TalkingTurkishEf.Entities.Voice", "Voice")
                        .WithMany()
                        .HasForeignKey("VoiceId");
                });

            modelBuilder.Entity("TalkingTurkishEf.Entities.Voice", b =>
                {
                    b.HasOne("TalkingTurkishEf.Entities.Language", "Languange")
                        .WithMany()
                        .HasForeignKey("LanguangeId");
                });
#pragma warning restore 612, 618
        }
    }
}
